/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package words.leisure.wallpapermaker;

public final class R {
    public static final class anim {
        public static final int APKTOOL_DUMMY_2=0x7f060002;
        public static final int translate_dialog_in=0x7f060000;
        public static final int translate_dialog_in_top=0x7f060003;
        public static final int translate_dialog_out=0x7f060001;
        public static final int translate_dialog_out_top=0x7f060004;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int ripple_one=0x7f020001;
        public static final int ripple_two=0x7f020002;
        public static final int welcome=0x7f020003;
    }
    public static final class id {
        public static final int lookListView1=0x7f050000;
        public static final int mainCardView1=0x7f050001;
        public static final int mainImageView1=0x7f050008;
        public static final int mainLinearLayout1=0x7f050002;
        public static final int mainTextView1=0x7f050005;
        public static final int mainTextView2=0x7f050004;
        public static final int mainTextView3=0x7f050003;
        public static final int shaonvGridView1=0x7f050006;
        public static final int ta_waitview=0x7f050009;
        public static final int webviewFrameLayout1=0x7f050007;
    }
    public static final class layout {
        public static final int APKTOOL_DUMMY_4=0x7f030004;
        public static final int logo=0x7f030005;
        public static final int look=0x7f030000;
        public static final int main=0x7f030001;
        public static final int shaonv=0x7f030002;
        public static final int webview=0x7f030003;
    }
    public static final class string {
        public static final int accsibility_service_description=0x7f080000;
        public static final int app_name=0x7f080001;
    }
    public static final class style {
        public static final int APKTOOL_DUMMY_1e=0x7f04001e;
        public static final int APKTOOL_DUMMY_1f=0x7f04001f;
        public static final int Animation_AppCompat_Dialog=0x7f040025;
        public static final int AppLuaDialog=0x7f040027;
        public static final int AppLua_ye=0x7f04002a;
        public static final int AppTheme1=0x7f040000;
        public static final int AppTheme10=0x7f040012;
        public static final int AppTheme11=0x7f040014;
        public static final int AppTheme12=0x7f040016;
        public static final int AppTheme13=0x7f040018;
        public static final int AppTheme14=0x7f04001d;
        public static final int AppTheme15=0x7f04001b;
        public static final int AppTheme16=0x7f040021;
        public static final int AppTheme17=0x7f040023;
        public static final int AppTheme18=0x7f040029;
        public static final int AppTheme2=0x7f040002;
        public static final int AppTheme3=0x7f040004;
        public static final int AppTheme4=0x7f040006;
        public static final int AppTheme5=0x7f040008;
        public static final int AppTheme6=0x7f04000a;
        public static final int AppTheme7=0x7f04000c;
        public static final int AppTheme8=0x7f04000e;
        public static final int AppTheme9=0x7f040010;
        public static final int AppThemeActivity=0x7f04002c;
        public static final int AppTheme_bai=0x7f04002f;
        public static final int Base_Animation_AppCompat_Dialog=0x7f040026;
        public static final int BottomDialog_Animation=0x7f040024;
        public static final int BottomDialog_Animation_Top=0x7f04002d;
        public static final int DialogTheme1=0x7f040001;
        public static final int DialogTheme10=0x7f040013;
        public static final int DialogTheme11=0x7f040015;
        public static final int DialogTheme12=0x7f040017;
        public static final int DialogTheme13=0x7f040019;
        public static final int DialogTheme14=0x7f04001c;
        public static final int DialogTheme15=0x7f04001a;
        public static final int DialogTheme16=0x7f040020;
        public static final int DialogTheme17=0x7f040022;
        public static final int DialogTheme18=0x7f040028;
        public static final int DialogTheme2=0x7f040003;
        public static final int DialogTheme3=0x7f040005;
        public static final int DialogTheme4=0x7f040007;
        public static final int DialogTheme5=0x7f040009;
        public static final int DialogTheme6=0x7f04000b;
        public static final int DialogTheme7=0x7f04000d;
        public static final int DialogTheme8=0x7f04000f;
        public static final int DialogTheme9=0x7f040011;
        public static final int DialogThemeActivity=0x7f04002b;
        public static final int DialogTheme_bai=0x7f04002e;
        public static final int MUKTheme=0x7f040030;
        public static final int MUKTheme_Light=0x7f040031;
    }
    public static final class xml {
        public static final int accessibility_service_config=0x7f070000;
        public static final int androlua_filepaths=0x7f070001;
    }
}
